name: shogi-bot
platform: nodejs
buildTool: yarn
version: 0.0.1
functions:
  info:
    handler: handler.info
    description: Basic Info
    events:
      - http:
          path: /
          method: get
          cors: true
  dump:
    handler: handler.dump
    description: Bot Dump
    events:
      - http:
          path: /dump
          method: get
          cors: true
  join:
    handler: handler.join
    description: Joins the party
    events:
      - http:
          path: /join
          method: get
          cors: true
  start:
    handler: handler.start
    description: Starts a new game
    events:
      - http:
          path: /start
          method: get
          cors: true
